[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Michael-F-Bryan <michaelfbryan@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
build = "build.rs"

[build-dependencies]
futhark-build = { git = "https://github.com/Michael-F-Bryan/futhark-rs" }
